# Generated by Django 5.1.2 on 2024-10-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(10, 'Easy'), (20, 'Medium'), (30, 'Hard')], null=True),
        ),
    ]
