# Generated by Django 5.1.2 on 2024-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasks_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=30, null=True),
        ),
    ]
